//Healing macro

Sub main() 

//hard coded my tank
/target "Jabopie"
/echo Starting mac

//loops healing until i do /end mac
/while (1) {
	/call Heal
	/delay 3s
}

/echo ending mac
/return

	
	
	
Sub Heal()

//debug print if i dont heal
/if (${Target.PctHPs} >= 90) {
	/echo health is good. it is ${Target.PctHPs}
} else {
	/while (${Target.PctHPs} < 90) {
		/echo healing because health is ${Target.PctHPs}
		/cast Minor Healing 
		/delay 3s
	}
}

/return